/**
 * Canonical Meccha Chameleon Workshop map catalog.
 * Run `npm run fetch:workshop` to sync preview URLs and stats from Steam API.
 */
export const WORKSHOP_CATALOG = [
  // --- existing 12 ---
  { id: "3743061744", slug: "minecraft", title: "Minecraft", author: "Skolas", category: "competitive", colors: 6, description: "Blocky village layout with familiar textures. Great for groups learning custom maps — trees, crafting tables, and wood tones offer varied hides.", tags: ["Community pick", "Sandbox", "Steam Workshop"], submittedAt: "2026-06-11" },
  { id: "3744444104", slug: "cs2-mirage", title: "CS2 Mirage", author: "bendawg2010", category: "competitive", colors: 5, description: "Counter-Strike Mirage layout with lanes, corners, and elevation. Familiar for FPS players — strong for organized seeker sweeps.", tags: ["Competitive", "CS", "Steam Workshop"], submittedAt: "2026-06-13" },
  { id: "3745249764", slug: "meeting-room", title: "Meeting room", author: "acid_fox", category: "competitive", colors: 5, description: "Modern office interior with reception, cafeteria, and dense office props. Strong silhouette-breaking furniture.", tags: ["Office", "Realistic", "Steam Workshop"], submittedAt: "2026-06-14" },
  { id: "3742794683", slug: "swimming-pool", title: "Swimming pool!", author: "Popunia", category: "funny", colors: 6, description: "Small painted-style pool map. Bright colors and hand-drawn walls — community favorite for chaotic funny rounds.", tags: ["Funny", "Pool", "Steam Workshop"], submittedAt: "2026-06-11" },
  { id: "3742253936", slug: "skeld", title: "Skeld (Imported)", author: "Just Nitro", category: "competitive", colors: 4, description: "Among Us Skeld recreation — engine room, medbay, reactor corridors. IP-familiar layout for quick pickup games.", tags: ["Among Us", "Steam Workshop"], submittedAt: "2026-06-10" },
  { id: "3742454367", slug: "fnaf-security-breach", title: "FNAF Security Breach - PARTS & SERVICE", author: "Just Nitro", category: "horror", colors: 5, description: "Five Nights at Freddy's Parts & Service area. Eerie machinery and dark metal tones — horror workshop staple.", tags: ["Horror", "FNAF", "Steam Workshop"], submittedAt: "2026-06-10" },
  { id: "3744930374", slug: "simpsons-family-house", title: "Simpsons Family House", author: "Nico", category: "funny", colors: 7, description: "Simpsons living room and kitchen interior. Instantly readable props — trending in community lobbies.", tags: ["Funny", "IP", "Trending"], submittedAt: "2026-06-14" },
  { id: "3745371103", slug: "low-poly-caverns", title: "Low Poly Caverns", author: "Hyas", category: "horror", colors: 4, description: "Low-poly cave camp scene. Dark values and simple shapes — good horror atmosphere for small lobbies.", tags: ["Horror", "Caves", "Steam Workshop"], submittedAt: "2026-06-15" },
  { id: "3745442455", slug: "maplestory-lacheln", title: "Maplestory Lacheln", author: "Skolas", category: "new", colors: 6, description: "MapleStory Lacheln recreation. Prop-dense rooms from the same creator as the Minecraft map — rising community interest.", tags: ["New", "IP", "Steam Workshop"], submittedAt: "2026-06-22" },
  { id: "3745191968", slug: "restaurant-building", title: "Restaurant Building", author: "Zeminah", category: "new", colors: 5, description: "Messy restaurant with storage and bathroom. Table clutter creates strong hide shapes in tight spaces.", tags: ["New", "Restaurant", "Steam Workshop"], submittedAt: "2026-06-23" },
  { id: "3745736909", slug: "the-market", title: "The Market", author: "Tunep", category: "funny", colors: 5, description: "Rustic village market with stalls and cottages. Cute palette — easy color matching for casual nights.", tags: ["Market", "Casual", "Steam Workshop"], submittedAt: "2026-06-12" },
  { id: "3746319788", slug: "low-poly-mini-town", title: "Low Poly Mini Town", author: "Zeminah", category: "new", colors: 4, description: "Compact low-poly town from the Restaurant Building creator. Newly listed — hiding spot guides coming soon.", tags: ["New", "Low poly", "Coming soon"], submittedAt: "2026-06-25", curated: false },
  // --- expanded catalog (18 new) ---
  { id: "3744672676", slug: "art-gallery", title: "Art Gallery", author: "Popunia", category: "funny", colors: 6, description: "Museum with famous paintings and portraits on the walls. Paint yourself into the Mona Lisa or blend with the floor — unique body-paint mechanics.", tags: ["Funny", "Museum", "Steam Workshop"], submittedAt: "2026-06-12" },
  { id: "3743930257", slug: "mario-kart", title: "Mario Kart", author: "Community", category: "funny", colors: 6, description: "Colorful arena imported from Team Fortress 2. Stairs, ramps, and iconic zones — perfect for Infection mode.", tags: ["IP", "Racing", "Steam Workshop"], submittedAt: "2026-06-11" },
  { id: "3746909981", slug: "viking-dining", title: "Viking Dining", author: "RareKiwi", category: "funny", colors: 5, description: "Viking tavern with shields, swords, spears, and ale. Scattered props on a compact map — great for prop mimic.", tags: ["Tavern", "Casual", "Steam Workshop"], submittedAt: "2026-06-16" },
  { id: "3747815568", slug: "police-station", title: "Police Station", author: "Community", category: "competitive", colors: 5, description: "Balanced law-enforcement interior with desks, cells, and corridors. Works well with a single hunter.", tags: ["Office", "Balanced", "Steam Workshop"], submittedAt: "2026-06-20" },
  { id: "3749628558", slug: "fall-guys-level", title: "Fall Guys Level", author: "ArenaCloser12", category: "funny", colors: 5, description: "Flat colorful platforms and trinkets — easy to paint and hide in plain sight. Meme lobby favorite.", tags: ["Funny", "Fall Guys", "Steam Workshop"], submittedAt: "2026-06-24" },
  { id: "3747027518", slug: "strike-zone-bowling", title: "Strike Zone Bowling Alley", author: "Community", category: "funny", colors: 5, description: "Bowling alley lanes and seating — mind games and deception in a neon-lit interior.", tags: ["Bowling", "Deception", "Steam Workshop"], submittedAt: "2026-06-18" },
  { id: "3746389744", slug: "minecraft-house", title: "Minecraft House", author: "IAmChriss_", category: "funny", colors: 6, description: "Survival house with a large yard. Hide as a torch, flower, or grass block — inside and outside hides.", tags: ["Minecraft", "Casual", "Steam Workshop"], submittedAt: "2026-06-16" },
  { id: "3744346760", slug: "the-village", title: "The Village", author: "Tunep", category: "competitive", colors: 6, description: "Expanded rustic village from The Market creator. Houses, roads, and props across a large play area — best with 2+ hunters.", tags: ["Village", "Large map", "Steam Workshop"], submittedAt: "2026-06-13" },
  { id: "3745148802", slug: "mw2-terminal", title: "MW2 Terminal (Interior Only)", author: "vegal", category: "competitive", colors: 5, description: "Modern Warfare 2 airport terminal interior. Large map with dense hiding spots — recommend 8+ players.", tags: ["FPS", "Large map", "Steam Workshop"], submittedAt: "2026-06-14" },
  { id: "3743176754", slug: "cs-office", title: "cs_Office", author: "bendawg2010", category: "competitive", colors: 5, description: "Counter-Strike Office port with familiar callouts. Tight corridors for organized seeker sweeps.", tags: ["Competitive", "CS", "Steam Workshop"], submittedAt: "2026-06-10" },
  { id: "3744197529", slug: "polyhouses", title: "PolyHouses", author: "SeanM", category: "funny", colors: 5, description: "Colorful low-poly houses with clear object silhouettes. Easy palette for casual workshop nights.", tags: ["Low poly", "Casual", "Steam Workshop"], submittedAt: "2026-06-13" },
  { id: "3745738734", slug: "de-dust2", title: "de_dust2", author: "bendawg2010", category: "competitive", colors: 5, description: "Legendary Counter-Strike dust2 ported from CS2. Massive layout — best for experienced groups.", tags: ["Competitive", "CS", "Steam Workshop"], submittedAt: "2026-06-15" },
  { id: "3742153036", slug: "charlie", title: "Charlie", author: "tindolt", category: "funny", colors: 2, description: "The white room of doom. Minimal palette with fixed lighting — sampling speed test in meme format.", tags: ["Meme", "Minimal", "Steam Workshop"], submittedAt: "2026-06-10" },
  { id: "3744068706", slug: "courage-cowardly-dog", title: "Courage the Cowardly Dog", author: "Community", category: "horror", colors: 5, description: "Bagge family farmhouse from Courage the Cowardly Dog. Eerie interior with recognizable cartoon props.", tags: ["Horror", "IP", "Steam Workshop"], submittedAt: "2026-06-12" },
  { id: "3742926910", slug: "fnaf-2-pizzeria", title: "FNAF 2 Pizzeria", author: "bendawg2010", category: "horror", colors: 5, description: "Five Nights at Freddy's pizzeria with party-room theming. Multiple rooms for varied horror hides.", tags: ["Horror", "FNAF", "Steam Workshop"], submittedAt: "2026-06-11" },
  { id: "3744940322", slug: "black-ops-2-raid", title: "Black Ops 2 Raid", author: "Community", category: "competitive", colors: 5, description: "Call of Duty Black Ops 2 Raid layout. Tactical lanes and elevation for competitive seeker sweeps.", tags: ["FPS", "Competitive", "Steam Workshop"], submittedAt: "2026-06-14" },
  { id: "3746167196", slug: "mitas-apartment", title: "Mita's Apartment 【MiSide】", author: "fujinn", category: "new", colors: 6, description: "MiSide apartment recreation. Exploration-heavy layout with detailed interior rooms and props.", tags: ["New", "IP", "Steam Workshop"], submittedAt: "2026-06-21" },
];
